-- MySQL Script generated by MySQL Workbench
-- sáb 01 dic 2018 00:02:06 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `nombre` VARCHAR(45) NOT NULL,
  `padre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`cobrable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cobrable` (
  `nombre` VARCHAR(45) NOT NULL,
  `tamaño` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(20,2) NOT NULL,
  `tipo` ENUM('VINO', 'ITEM_CARTA', 'MENU_PROMOCIONAL', '') NOT NULL,
  PRIMARY KEY (`nombre`, `tamaño`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`solicitud` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_cobrable` VARCHAR(45) NOT NULL,
  `tamaño_cobrable` VARCHAR(45) NOT NULL,
  `cantidad` INT(10) UNSIGNED NOT NULL,
  `precio` DECIMAL(20,2) NOT NULL,
  `estado` ENUM('PEDIDO', 'COCINANDO', 'COCINADO', 'ENTREGADO', 'COBRADO') NOT NULL,
  `observaciones` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_solicitud_cobrable` (`nombre_cobrable` ASC, `tamaño_cobrable` ASC) VISIBLE,
  CONSTRAINT `fk_solicitud_cobrable`
    FOREIGN KEY (`nombre_cobrable` , `tamaño_cobrable`)
    REFERENCES `mydb`.`cobrable` (`nombre` , `tamaño`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`mozo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mozo` (
  `nro_mozo` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `dni` INT(8) UNSIGNED NULL,
  `cuil` INT(11) NOT NULL,
  `telefono` INT(10) NULL,
  PRIMARY KEY (`nro_mozo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comanda` (
  `id_solicitud` INT(10) UNSIGNED NOT NULL,
  `fecha` DATE NOT NULL,
  `mesa` INT(11) NOT NULL,
  `cantidad_comensales` INT(11) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `estado` ENUM('abierta', 'cerrada') NULL DEFAULT NULL,
  `nro_mozo` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_solicitud`, `fecha`, `mesa`),
  INDEX `fk_comanda_mozo` (`nro_mozo` ASC) VISIBLE,
  CONSTRAINT `fk_comanda_solicitud`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `mydb`.`solicitud` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_comanda_mozo`
    FOREIGN KEY (`nro_mozo`)
    REFERENCES `mydb`.`mozo` (`nro_mozo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`item_carta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item_carta` (
  `nombre` VARCHAR(45) NOT NULL,
  `tamaño` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `categoria` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`nombre`, `tamaño`),
  INDEX `fk_item_carta_categoria` (`categoria` ASC) VISIBLE,
  CONSTRAINT `fk_item_carta_categoria`
    FOREIGN KEY (`categoria`)
    REFERENCES `mydb`.`categoria` (`nombre`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_item_carta_cobrable`
    FOREIGN KEY (`nombre` , `tamaño`)
    REFERENCES `mydb`.`cobrable` (`nombre` , `tamaño`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`menu_promocional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`menu_promocional` (
  `nombre` VARCHAR(45) NOT NULL,
  `tamaño` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `dias_de_la_semana` INT(10) UNSIGNED NOT NULL COMMENT 'Máscara de bits con los dias de la semana en que el menu está disponible, empezando por Lunes.',
  `tipo` INT(11) NOT NULL,
  PRIMARY KEY (`nombre`, `tamaño`),
  CONSTRAINT `fk_menu_cobrable`
    FOREIGN KEY (`nombre` , `tamaño`)
    REFERENCES `mydb`.`cobrable` (`nombre` , `tamaño`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`paso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paso` (
  `nombre_menu` VARCHAR(45) NOT NULL,
  `tamaño_menu` VARCHAR(45) NOT NULL,
  `nombre_item` VARCHAR(45) NOT NULL,
  `tamaño_item` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_menu`, `tamaño_menu`, `nombre_item`, `tamaño_item`),
  INDEX `fk_paso_item` (`nombre_item` ASC, `tamaño_item` ASC) VISIBLE,
  CONSTRAINT `fk_paso_item`
    FOREIGN KEY (`nombre_item` , `tamaño_item`)
    REFERENCES `mydb`.`item_carta` (`nombre` , `tamaño`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_paso_menu`
    FOREIGN KEY (`nombre_menu` , `tamaño_menu`)
    REFERENCES `mydb`.`menu_promocional` (`nombre` , `tamaño`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`vino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vino` (
  `nombre` VARCHAR(45) NOT NULL,
  `tamaño` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `bodega` VARCHAR(45) NOT NULL,
  `variedad_uva` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`nombre`, `tamaño`, `color`, `bodega`),
  CONSTRAINT `fk_vino_cobrable`
    FOREIGN KEY (`nombre` , `tamaño`)
    REFERENCES `mydb`.`cobrable` (`nombre` , `tamaño`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`factura` (
  `nro_factura` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha_comanda` DATE NOT NULL,
  `mesa_comanda` INT(11) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `importe` DECIMAL(20,2) NOT NULL,
  PRIMARY KEY (`nro_factura`),
  INDEX `fk_comanda_factura` (`fecha_comanda` ASC, `mesa_comanda` ASC) VISIBLE,
  CONSTRAINT `fk_comanda_factura`
    FOREIGN KEY (`fecha_comanda` , `mesa_comanda`)
    REFERENCES `mydb`.`comanda` (`fecha` , `mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cupon` (
  `nro_cupon` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero_factura` INT(10) UNSIGNED NOT NULL,
  `nro_tarjeta_pago` INT(16) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `nro_comprobante` INT(10) NOT NULL,
  `codigo_autorizacion` INT(10) NOT NULL,
  PRIMARY KEY (`nro_cupon`),
  INDEX `fk_factura_cupon` (`numero_factura` ASC) VISIBLE,
  CONSTRAINT `fk_factura_cupon`
    FOREIGN KEY (`numero_factura`)
    REFERENCES `mydb`.`factura` (`nro_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`direccion_mozo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`direccion_mozo` (
  `calle` VARCHAR(45) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `numeracion` INT(6) ZEROFILL NOT NULL,
  `nro_mozo` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`calle`, `localidad`, `numeracion`, `nro_mozo`),
  INDEX `fk_mozo_direccion` (`nro_mozo` ASC) VISIBLE,
  CONSTRAINT `fk_direccion_mozo`
    FOREIGN KEY (`nro_mozo`)
    REFERENCES `mydb`.`mozo` (`nro_mozo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
